name: Add labels

on:
  workflow_dispatch:
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display PRs
        uses: ./.github/actions/pyactions
        with:
          script: |
            for pr in api.pulls.get():
                with _log.group(pr.title):
                    print(pr)

