name: Add labels

on:
  workflow_dispatch:
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Display PRs
        uses: ./.github/actions/pyactions
        with:
          script: |
            for pr in api.pulls.list():
                title = f'PR#{pr.number} - {pr.title}'
                with _log.group(title):
                    print(pr)

