name: Integration

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:


jobs:
  my_job:
    runs-on: ubuntu-latest
    # if: (github.event.action == 'labeled') && (github.event.label.name == 'CI:run')
    # if: (!contains(github.event_name, 'pull_request') || (startswith(github.event.label.name, 'CI:run') && endswith(github.event.label.name, github.workflow)))
    if: >-
      (
        github.event.action != 'labeled'
        ||
        (
          contains(github.event.label.description, 'triggers_workflow')
          &&
          contains(github.event.label.description, github.workflow)
        )
      )
    steps:
      - name: Wait a bit
        run: sleep 30; echo "Done!"
