name: Integration

on:
  pull_request:
    types: [labeled]
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    if: (github.event.action != 'labeled') || (github.event.label.name == 'CI:run')
    steps:
      - name: Wait a bit
        run: sleep 30; echo "Done!"
