name: Post Integration

on:
  workflow_run:
    workflows: [Integration]
    types: [completed]
    # branches-ignore:
    #   - main

jobs:
  reset_triggers:
    name: Display event info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyactions
        name: Display contexts
        with:
          script: |
            _log.display("context_github", context_github)
