name: Post Integration

on:
  workflow_run:
    workflows: [Integration]
    types: [completed]
    branches-ignore:
      - main

jobs:
  reset_triggers:
    name: Display event info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyactions
        name: Display contexts
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        with:
          script: |
            _log.display("context_github", context_github)
      - uses: ./.github/actions/pyactions
        name: Reset trigger
        # if: github.event.workflow_run.pull_requests != []
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          GITHUB_TOKEN: ${{ secrets.PYACTIONS_TOKEN }}
        with:
          script: |
            _log.display("context_github", context_github)
            prs = context_github.event.workflow_run.pull_requests
            trigger = LabelAddTrigger("CI:run")
            for pr in prs:
                _log.display(f'PR #{pr.number}', pr)
                trigger.reset(api, target=pr)
