name: Post Integration

on:
  workflow_run:
    workflows: [Integration]
    types: [completed]
    branches-ignore:
      - main

jobs:
  reset_triggers:
    name: Display event info
    runs-on: ubuntu-latest
    # if: github.event.workflow_run.pull_requests[0] != null
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyactions
        name: Display contexts
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        with:
          script: |
            log.display(github=github)
            log.display(github__event=github.event)
      - uses: ./.github/actions/pyactions
        name: Reset trigger
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          GITHUB_TOKEN: ${{ secrets.PYACTIONS_TOKEN }}
        with:
          script: |
            log.display(context_github=context_github)
            prs = context_github.event.workflow_run.pull_requests
            trigger = LabelAddTrigger("CI:run")
            for pr in prs:
                log.display(pr=pr) 
                trigger.reset(api, target=pr)
