name: PR Review

on:
  pull_request_review:
    types: [submitted]


jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyactions
        name: Display event
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        with:
          script: |
            _log.display("github", github)
            _log.display("github.event", github.event)
      - uses: ./.github/actions/pyactions
        name: Analyze reviews
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          GITHUB_TOKEN: ${{ secrets.PYACTIONS_TOKEN }}  # needed to access the branch protection
        with:
          script: |
            from .reviews import PullReviews
            pr = github.event.pull_request
            _log.display("pr", pr)
            reviews = PullReviews.fetch(api, pr=pr)
            _log.display("reviews.latest_by_user", reviews.latest_by_user)
