name: PR Review

on:
  pull_request_review:
    types: [submitted]


jobs:
  check-approval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pyactions
        name: Display event
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
        with:
          script: |
            log.display(github=github)
            log.display(github__event=github.event)
      - uses: ./.github/actions/pyactions
        name: Analyze reviews
        env:
          CONTEXT_GITHUB: ${{ toJSON(github) }}
          GITHUB_TOKEN: ${{ secrets.PYACTIONS_TOKEN }}  # needed to access the branch protection
        with:
          script: |
            from .reviews import PullReviews
            pr = github.event.pull_request
            log.display(pr=pr)
            reviews = PullReviews.fetch(api, pr=pr)
            log.display(reviews.latest_by_user, "reviews.latest_by_user")
            log.info(f'{reviews.is_status_approved=}')
